name: Snake Commit

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: windows-latest
    steps:
      # Snake Animation
      - uses: actions/setup-node@v1
        id: snake-gif
        with:
         node-version: '10.x'
          github_user_name: LaturbDevs
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
